version: "3.9"
services:
  runner:
    env_file: .env
    build: 
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${UID}
        - USER_GID=${GID}
        - CONDA_ENV_NAME=${CONDA_ENV_NAME}
      context: .
      dockerfile: Dockerfile-compose
    image: ortools:${TAG}
    stdin_open: true
    volumes:
      - ..:/${MODULE_NAME}
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro