FROM continuumio/miniconda3







# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************



# VARIABLES
ARG PATH="/root/miniconda3/bin:${PATH}"
ARG ENVNAME="ortools"
ARG USERNAME="vscode"
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME


#SHELL ["/bin/bash", "--login", "-c"]
ENV PATH="/opt/conda:${PATH}"
RUN apt-get update \
    && apt-get install -y wget \
    git \
     && rm -rf /var/lib/apt/lists/*

RUN sudo apt install bash-completion -y

#RUN sudo chown 1000:1000 /opt/conda/pkgs/urls.txt
# [Optional] Set the default user. Omit if you want to keep the default as root.
RUN sudo chown -R $USER:$USER "/opt/conda/"
USER $USERNAME
# RUN conda create --name $ENVNAME
# RUN echo "conda activate $ENVNAME" >> ~/.bashrc
# SHELL ["/bin/bash", "--login", "-c"]
# # Conda installs
# RUN conda install -y -c conda-forge ortools-python ipython \
#     pandas xlrd xlwt pytables \
#     pre-commit black

#RUN conda install -c conda-forge click=8.0.4

#RUN rm /etc/environment
#RUN echo "LANG=en_US.utf-8" > /etc/environment
#RUN echo "LC_ALL=en_US.utf-8" > /etc/environment

# RUN dpkg-reconfigure locales
# RUN locale-gen
#SHELL ["/bin/bash", "--login", "-c"]
