name: scheduling
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipython
  - pre-commit
  - pytest
  - pandas
  - yaml
  - pytables
  - xlrd
  - xlwt
  - xlsxwriter
  - numpy
  - openpyxl
  - scipy
  - networkx
  - matplotlib
  - sqlalchemy
  - just
  - pip:
    - ortools
    - mermaid-py
